spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  mongodb:
    host: ${MONGODB_HOST:44.221.50.201}
    port: ${MONGODB_PORT:27017}
    database: ${MONGODB_DB:order_db}
openapi:
  service:
    api-docs: order-service
    server: ${HOST_NAME:http://localhost}:8085
    title: Order service
    version: 1.0.0