server:
  port: 8085
spring:
  application:
    name: order-service
  profiles:
    active: @spring.profiles.active@

management: # Health check
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO
    web: OFF
