server:
  port: 4953

spring:
  application:
    name: api-gateway
  profiles:
    active: dev

management: # show information service's health
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO
    org.springframework: INFO