spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
          routes:
            - id: authentication-service
              uri: http://${HOST_NAME:localhost}:8081/auth
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /$\{segment}
                - CustomizeFilter
            - id: account-service
              uri: http://${HOST_NAME:localhost}:8082
              predicates:
                - Path=/account/**
              filters:
                - RewritePath=/account/(?<segment>.*), /$\{segment}
                - CustomizeFilter
            - id: product-service
              uri: http://${HOST_NAME:localhost}:8083
              predicates:
                - Path=/product/**
              filters:
                - RewritePath=/product/(?<segment>.*), /$\{segment}
                - CustomizeFilter