spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "http://localhost:5173"
                allowedHeaders: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
          routes:
            - id: authentication-service
              uri: http://${HOST_NAME:localhost}:8081/auth
              predicates:
                - Path=/auth/**, /v3/api-docs/authentication-service
              filters:
                - RewritePath=/auth/(?<segment>.*), /$\{segment}
                - CustomizeFilter
            - id: account-service
              uri: http://${HOST_NAME:localhost}:8082
              predicates:
                - Path=/account/**, /v3/api-docs/account-service
              filters:
                - RewritePath=/account/(?<segment>.*), /$\{segment}
                - CustomizeFilter
            - id: product-service
              uri: http://${HOST_NAME:localhost}:8083
              predicates:
                - Path=/product/**, /v3/api-docs/product-service
              filters:
                - RewritePath=/product/(?<segment>.*), /$\{segment}
                - CustomizeFilter
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /v3/api-docs/authentication-service
        name: Authentication Service
      - url: /v3/api-docs/account-service
        name: Account Service
      - url: /v3/api-docs/product-service
        name: Product Service
      - url: /v3/api-docs/order-service
        name: Order Service
      - url: /v3/api-docs/inventory-service
        name: Inventory Service
      - url: /v3/api-docs/mail-service
        name: Mail Service