spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  elasticsearch:
    uris: ${ELASTICSEARCH_HOST:DUMMY_URL}
    username: ${ELASTICSEARCH_USERNAME:DUMMY_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD:DUMMY_PASSWORD}
openapi:
  service:
    api-docs: product-service
    server: ${HOST_NAME:http://localhost}:8083
    title: Product service
    version: 1.0.0